/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/carpet.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Carpet(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/assets/carpet-transformed.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials.seat2}
          position={[5.02, 0, 4.67]}
          scale={[2.84, 0.04, 2.84]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/carpet-transformed.glb");
