/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/chair.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Chair(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/assets/chair-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="chair"
          position={[3.12, 0, 2.9]}
          rotation={[0, -0.85, 0]}
          scale={0.2}
        >
          <mesh
            name="Cylinder006"
            geometry={nodes.Cylinder006.geometry}
            material={materials["wall.001"]}
          />
          <mesh
            name="Cylinder006_1"
            geometry={nodes.Cylinder006_1.geometry}
            material={materials.wheels}
          />
          <mesh
            name="Cylinder006_2"
            geometry={nodes.Cylinder006_2.geometry}
            material={materials.seat2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chair-transformed.glb");
