/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/keyboard.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Keyboard(props) {
  const { nodes, materials } = useGLTF("/assets/keyboard-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials.keyboard}
        position={[4.26, 2.27, 1.65]}
        rotation={[0, 0.32, 0]}
        scale={[0.82, 1.39, 0.44]}
      />
    </group>
  );
}

useGLTF.preload("/keyboard-transformed.glb");
