/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/monitor.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Monitor(props) {
  const { nodes, materials } = useGLTF("/assets/monitor-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[3.97, 2.19, 0.69]}
        rotation={[Math.PI / 2, 0, -0.32]}
        scale={[1.23, 0.66, 0.66]}
      >
        <mesh geometry={nodes.Plane006.geometry} material={materials.monitor} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.tv} />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials.mouse} />
      </group>
    </group>
  );
}

useGLTF.preload("/monitor-transformed.glb");
