/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/mouse.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Mouse(props) {
  const { nodes, materials } = useGLTF("/assets/mouse-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mpm_f19__Apple_Magic_Mouse.geometry}
        material={materials.mouse}
        position={[5.63, 2.26, 1.65]}
        rotation={[Math.PI / 2, 0, 0.39]}
        scale={0.004}
      />
    </group>
  );
}

useGLTF.preload("/mouse-transformed.glb");
