/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/pot.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Pot(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/assets/pot-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="flower-pot" position={[0.7, 0, 9.02]} scale={0.66}>
          <mesh
            name="Cylinder001"
            geometry={nodes.Cylinder001.geometry}
            material={materials.wood}
          />
          <mesh
            name="Cylinder001_1"
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.soil}
          />
          <mesh
            name="Cylinder001_2"
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["3dplant_SmallBalsam_thin"]}
          />
          <mesh
            name="Cylinder001_3"
            geometry={nodes.Cylinder001_3.geometry}
            material={materials["3dplant_SmallBalsam_dolid"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pot-transformed.glb");
