/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Title from "./Title";
import Table from "./Table";
import Chair from "./Chair";
import Pot from "./Pot";
import Carpet from "./Carpet";
import Shoes from "./Shoes";

export default function Room(props) {
  const { nodes, materials } = useGLTF("/assets/room-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <group scale={5}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.wall} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.floor} />
      </group>
      <Chair />
      <Title />
      <Table />
      <Pot />
      {/* <Carpet /> */}
      <Shoes />
    </group>
  );
}

useGLTF.preload("/room-transformed.glb");
