/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/shoes.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Shoes(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/assets/shoes-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="shoes" position={[8, 0.1, 9]} scale={0.22}>
          <mesh
            name="Plane003"
            geometry={nodes.Plane003.geometry}
            material={materials["wall.003"]}
          />
          <mesh
            name="Plane003_1"
            geometry={nodes.Plane003_1.geometry}
            material={materials.seat2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shoes-transformed.glb");
