/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/table.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Monitor from "./Monitor";
import Keyboard from "./Keyboard";
import Mouse from "./Mouse";

export default function Table(props) {
  const { nodes, materials } = useGLTF("/assets/table-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[5.49, 0.01, 1.61]} scale={[3.69, 1.39, 1.39]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials.drawer} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.seat2} />
      </group>
      <Monitor />
      <Keyboard />
      <Mouse />
    </group>
  );
}

useGLTF.preload("/table-transformed.glb");
