/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/title.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Title(props) {
  const group = useRef();

  const { nodes, materials, animations } = useGLTF(
    "/assets/title-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Text"
          position={[0.06, 2.97, 6.61]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={3.22}
        >
          <mesh
            name="Text_1"
            geometry={nodes.Text_1.geometry}
            material={materials.divyansh}
          />
          <mesh
            name="Text_2"
            geometry={nodes.Text_2.geometry}
            material={materials.falodiya}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/title-transformed.glb");
