/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/big-pot.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function BigPot(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/big-pot-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="pot" position={[13.01, 0, -6.42]} scale={2.01}>
                    <mesh
                        name="Cylinder005"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005.geometry}
                        material={materials.pot}
                    />
                    <mesh
                        name="Cylinder005_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_1.geometry}
                        material={materials.pot2}
                    />
                    <mesh
                        name="Cylinder005_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_2.geometry}
                        material={materials.soil}
                    />
                    <mesh
                        name="Cylinder005_3"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_3.geometry}
                        material={materials.leaf3}
                    />
                    <mesh
                        name="Cylinder005_4"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_4.geometry}
                        material={materials.leaf}
                    />
                    <mesh
                        name="Cylinder005_5"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_5.geometry}
                        material={materials.leaf2}
                    />
                    <mesh
                        name="Cylinder005_6"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_6.geometry}
                        material={materials.leaf4}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/big-pot-transformed.glb');
