/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/book1.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Book1(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/book1-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="book"
                    position={[-7, 19.75, -8.15]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[2.52, 1.37, 1.53]}
                >
                    <mesh
                        name="Plane027"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane027.geometry}
                        material={materials.book}
                    />
                    <mesh
                        name="Plane027_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane027_1.geometry}
                        material={materials.pages}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/book1-transformed.glb');
