/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/book2.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Book2(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/book2-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="book001"
                    position={[-7, 18.72, -8.15]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[2.74, 1.16, 1.67]}
                >
                    <mesh
                        name="Plane026"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane026.geometry}
                        material={materials.book2}
                    />
                    <mesh
                        name="Plane026_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane026_1.geometry}
                        material={materials.pages}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/book2-transformed.glb');
