/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/book-plank.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import Book1 from './Book1';
import Book2 from './Book2';
import SmallPot from './SmallPot';

export default function BookPlank(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/book-plank-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="plank"
                    castShadow
                    receiveShadow
                    geometry={nodes.plank.geometry}
                    material={materials.handles}
                    position={[-8.25, 17.89, -8.99]}
                    scale={[4.46, 1.37, 1]}
                />
            </group>
            <Book1 />
            <Book2 />
            <SmallPot />
        </group>
    );
}

useGLTF.preload('/book-plank-transformed.glb');
