/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/carpet.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Carpet(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/carpet-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="carpet"
                    position={[0, 0.41, 10.19]}
                    scale={[12.09, 12.09, 11.65]}
                >
                    <mesh
                        name="Plane009"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane009.geometry}
                        material={materials.carpet}
                    />
                    <mesh
                        name="Plane009_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane009_1.geometry}
                        material={materials.handles}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/carpet-transformed.glb');
