/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/chair.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Chair(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/chair-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="chair"
                    castShadow
                    receiveShadow
                    geometry={nodes.chair.geometry}
                    material={materials.table}
                    position={[0, 4.56, 7.7]}
                    scale={[1.88, 2.75, 2.75]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/chair-transformed.glb');
