/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/contact-plank.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import Github from './Github';
import Gmail from './Gmail';
import Linkedin from './Linkedin';

export default function ContactPlank(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/contact-plank-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="plank001"
                    castShadow
                    receiveShadow
                    geometry={nodes.plank001.geometry}
                    material={materials.handles}
                    position={[22.16, 23.88, -8.99]}
                    scale={[3.96, 1, 1]}
                />
            </group>
            <Github />
            <Gmail />
            <Linkedin />
        </group>
    );
}

useGLTF.preload('/contact-plank-transformed.glb');
