/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/cup.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Cup(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/cup-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="cup"
                    position={[5.99, 7.11, -7.26]}
                    scale={[0.56, 0.65, 0.56]}
                >
                    <mesh
                        name="Cylinder"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder.geometry}
                        material={materials.handles}
                    />
                    <mesh
                        name="Cylinder_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder_1.geometry}
                        material={materials.dirink}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/cup-transformed.glb');
