/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/github.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Github(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/github-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="github"
                    castShadow
                    receiveShadow
                    geometry={nodes.github.geometry}
                    material={materials.github}
                    position={[19.39, 23.88, -8.66]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={210.53}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/github-transformed.glb');
