/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/gmail.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Gmail(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/gmail-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="gmail"
                    position={[22.16, 23.88, -8.66]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={299.37}
                >
                    <mesh
                        name="Curve002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Curve002.geometry}
                        material={materials.gmail}
                    />
                    <mesh
                        name="Curve002_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Curve002_1.geometry}
                        material={materials.gmail2}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/gmail-transformed.glb');
