/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/monitor.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Monitor(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/monitor-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="stand"
                    position={[-0.58, 7.12, -7.29]}
                    scale={[1.29, 1, 1]}
                >
                    <mesh
                        name="Plane006"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane006.geometry}
                        material={materials.stand}
                    />
                    <mesh
                        name="Plane006_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane006_1.geometry}
                        material={materials.keyboard}
                    />
                    <mesh
                        name="Plane006_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane006_2.geometry}
                        material={materials.display}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/monitor-transformed.glb');
