/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/mouse.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Mouse(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/mouse-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="mouse"
                    position={[3.56, 7.17, -3.81]}
                    rotation={[0, 1.57, 0]}
                    scale={[0.48, 0.38, 0.41]}
                >
                    <mesh
                        name="Plane023"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane023.geometry}
                        material={materials.keyboard}
                    />
                    <mesh
                        name="Plane023_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane023_1.geometry}
                        material={materials.scroll}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/mouse-transformed.glb');
