/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/mousepad.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import Mouse from './Mouse';

export default function Mousepad(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/mousepad-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="mousepad"
                    castShadow
                    receiveShadow
                    geometry={nodes.mousepad.geometry}
                    material={materials.mousepad}
                    position={[3.56, 7.11, -3.81]}
                    rotation={[0, -0.32, 0]}
                    scale={[1.41, 1, 1.05]}
                />
            </group>
            <Mouse />
        </group>
    );
}

useGLTF.preload('/mousepad-transformed.glb');
