/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/phone.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Phone(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/phone-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="phone"
                    position={[6.77, 7.11, -4.59]}
                    rotation={[0, -0.37, 0]}
                    scale={[0.56, 0.92, 1.05]}
                >
                    <mesh
                        name="Plane030"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane030.geometry}
                        material={materials.keyboard}
                    />
                    <mesh
                        name="Plane030_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane030_1.geometry}
                        material={materials.display}
                    />
                    <mesh
                        name="Plane030_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane030_2.geometry}
                        material={materials.camera}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/phone-transformed.glb');
