/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/walls.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import Carpet from './Carpet';
import Chair from './Chair';
import Table from './Table';
import ContactPlank from './ContactPlank';
import BookPlank from './BookPlank';
import BigPot from './BigPot';

export default function Room(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/walls-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="walls"
                    castShadow
                    receiveShadow
                    geometry={nodes.walls.geometry}
                    material={materials.drawer}
                    scale={[17.33, 10.04, 10.04]}
                />
            </group>
            <Carpet />
            <Chair />
            <Table />
            <ContactPlank />
            <BookPlank />
            <BigPot />
        </group>
    );
}

useGLTF.preload('/walls-transformed.glb');
