/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/small-pot.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function SmallPot(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/small-pot-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="pot001"
                    position={[-11.13, 17.89, -7.67]}
                    scale={1.08}
                >
                    <mesh
                        name="Cylinder007"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder007.geometry}
                        material={materials.pot3}
                    />
                    <mesh
                        name="Cylinder007_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder007_1.geometry}
                        material={materials.cactus}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/small-pot-transformed.glb');
