/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/speaker.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Speaker(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/speaker-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="Plane"
                    position={[-7.49, 7.11, -5.8]}
                    rotation={[0, -1.16, 0]}
                >
                    <mesh
                        name="Plane035"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane035.geometry}
                        material={materials.speaker}
                    />
                    <mesh
                        name="Plane035_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane035_1.geometry}
                        material={materials.speark2}
                    />
                    <mesh
                        name="Plane035_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane035_2.geometry}
                        material={materials.speark2}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/speaker-transformed.glb');
