/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --shadows -T C:/Users/devf/Desktop/divyansh-app/public/assets/table.glb
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import Monitor from './Monitor';
import Mousepad from './Mousepad';
import Keyboard from './Keyboard';
import Speaker from './Speaker';
import Cup from './Cup';
import Phone from './Phone';

export default function Table(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        '/assets/table-transformed.glb'
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="table"
                    position={[-0.63, -0.01, -5.74]}
                    scale={[9.09, 4, 4]}
                >
                    <mesh
                        name="Plane002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002.geometry}
                        material={materials.table}
                    />
                    <mesh
                        name="Plane002_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_1.geometry}
                        material={materials.handles}
                    />
                    <mesh
                        name="Plane002_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_2.geometry}
                        material={materials.drawer}
                    />
                </group>
            </group>

            <Monitor />
            <Keyboard />
            <Mousepad />
            <Speaker />
            <Cup />
            <Phone />
        </group>
    );
}

useGLTF.preload('/table-transformed.glb');
